# Generated by Django 2.2.5 on 2019-09-25 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=100)),
                ('new_path', models.CharField(max_length=100)),
                ('change_type', models.CharField(choices=[('ADD', 'Added'), ('DEL', 'Deleted'), ('MOD', 'Modified'), ('REN', 'Renamed')], default='MOD', max_length=10)),
                ('diff', models.TextField()),
                ('source_code', models.TextField()),
                ('source_code_before', models.TextField()),
                ('added', models.IntegerField()),
                ('removed', models.IntegerField()),
                ('nloc', models.IntegerField()),
                ('complexity', models.IntegerField()),
                ('token_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=300)),
                ('msg', models.CharField(max_length=300)),
                ('author_date', models.DateField()),
                ('committer_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='contributions.Developer')),
                ('committer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committer_id', to='contributions.Developer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Project')),
            ],
        ),
    ]
