# Generated by Django 2.2.5 on 2019-10-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=300)),
                ('msg', models.CharField(max_length=300)),
                ('author_date', models.DateField()),
                ('committer_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectoryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cloc', models.IntegerField(default=0, null=True)),
                ('total_files', models.IntegerField(default=0, null=True)),
                ('total_commits', models.IntegerField(default=0, null=True)),
                ('cloc_threshold', models.FloatField(default=0, null=True)),
                ('file_threshold', models.FloatField(default=0, null=True)),
                ('commit_threshold', models.FloatField(default=0, null=True)),
                ('standard_deviation', models.FloatField(default=0, null=True)),
                ('media', models.FloatField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_path', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('previous_tag', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.Tag')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='contributions.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=200, null=True)),
                ('new_path', models.CharField(max_length=200, null=True)),
                ('path', models.CharField(default='-', max_length=200, null=True)),
                ('change_type', models.CharField(choices=[('ADD', 'Added'), ('DEL', 'Deleted'), ('MOD', 'Modified'), ('REN', 'Renamed')], default='MOD', max_length=10)),
                ('diff', models.TextField()),
                ('source_code', models.TextField(null=True)),
                ('source_code_before', models.TextField(null=True)),
                ('added', models.IntegerField(null=True)),
                ('removed', models.IntegerField(null=True)),
                ('cloc', models.IntegerField(default=0)),
                ('nloc', models.IntegerField(null=True)),
                ('complexity', models.IntegerField(null=True)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='contributions.Commit')),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='contributions.Directory')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloc', models.IntegerField(default=0, null=True)),
                ('files', models.IntegerField(default=0, null=True)),
                ('commits', models.IntegerField(default=0, null=True)),
                ('ownership_cloc', models.FloatField(default=0.0, null=True)),
                ('ownership_files', models.FloatField(default=0.0, null=True)),
                ('ownership_commits', models.FloatField(default=0.0, null=True)),
                ('experience', models.FloatField(default=0.0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contributions.Developer')),
                ('directory_report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contributions.DirectoryReport')),
            ],
        ),
        migrations.AddField(
            model_name='directoryreport',
            name='authors',
            field=models.ManyToManyField(through='contributions.IndividualContribution', to='contributions.Developer'),
        ),
        migrations.AddField(
            model_name='directoryreport',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='directory_reports', to='contributions.Directory'),
        ),
        migrations.AddField(
            model_name='directoryreport',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='directory_reports', to='contributions.Tag'),
        ),
        migrations.AddField(
            model_name='directory',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directories', to='contributions.Project'),
        ),
        migrations.AddField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='contributions.Developer'),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committer_id', to='contributions.Developer'),
        ),
        migrations.AddField(
            model_name='commit',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='contributions.Project'),
        ),
        migrations.AddField(
            model_name='commit',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='contributions.Tag'),
        ),
    ]
