# Generated by Django 2.2.5 on 2019-09-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0002_auto_20190925_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='commit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='contributions.Commit'),
            preserve_default=False,
        ),
    ]
