# Generated by Django 2.2.5 on 2019-09-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_modification_commit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='source_code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='source_code_before',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='token_count',
            field=models.IntegerField(null=True),
        ),
    ]
