# Generated by Django 2.2.5 on 2019-09-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_auto_20190926_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='old_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
