# Generated by Django 2.2.5 on 2019-10-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_auto_20191013_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directoryreport',
            old_name='media',
            new_name='mean',
        ),
        migrations.AddField(
            model_name='directoryreport',
            name='median',
            field=models.FloatField(default=0, null=True),
        ),
    ]
