# Generated by Django 2.2.5 on 2019-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_auto_20190926_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='token_count',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
