# Generated by Django 2.2.5 on 2019-10-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_auto_20191015_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualcontribution',
            name='abs_experience',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
