# Generated by Django 2.2.5 on 2019-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_auto_20190926_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='delta',
            field=models.IntegerField(default=0),
        ),
    ]
