# Generated by Django 2.2.5 on 2019-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0007_individualcontribution_abs_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualcontribution',
            name='bf_cloc',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='bf_commit',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='bf_file',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
