# Generated by Django 2.2.5 on 2019-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_modification_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='path',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='modification',
            name='new_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='old_path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
