# Generated by Django 2.2.5 on 2019-10-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0008_auto_20191023_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='cloc_exp',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='commit_exp',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='experience_bf',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='file_exp',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
