# Generated by Django 2.2.5 on 2019-10-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0009_auto_20191025_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualcontribution',
            name='ownership_cloc_in_this_tag',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='ownership_commits_in_this_tag',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='ownership_files_in_this_tag',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='previous_total_commits',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
