# Generated by Django 2.2.5 on 2019-09-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_auto_20190926_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='path',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
