# Generated by Django 2.2.5 on 2019-09-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_auto_20190926_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='path',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
    ]
