# Generated by Django 2.2.5 on 2019-10-29 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_auto_20191029_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualcontribution',
            name='previous_total_commits',
        ),
    ]
