# Generated by Django 2.2.5 on 2019-09-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_auto_20190926_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='directory',
            field=models.CharField(default='-', max_length=200, null=True),
        ),
    ]
