# Generated by Django 2.2.5 on 2019-10-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_remove_individualcontribution_previous_total_commits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualcontribution',
            name='ownership_cloc_in_this_tag',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='individualcontribution',
            name='ownership_commits_in_this_tag',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='individualcontribution',
            name='ownership_files_in_this_tag',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
