# Generated by Django 2.2.5 on 2019-11-06 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0012_auto_20191029_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='children_commit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_commits', to='contributions.Commit'),
        ),
    ]
