# Generated by Django 2.2.5 on 2019-11-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0013_commit_children_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='parents',
            field=models.CharField(default='exit', max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commit',
            name='children_commit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='contributions.Commit'),
        ),
    ]
