# Generated by Django 2.2.5 on 2019-10-09 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0013_auto_20191007_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='previous_tag',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.Tag'),
        ),
    ]
