# Generated by Django 2.2.5 on 2019-11-07 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0014_auto_20191107_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='parents',
            new_name='parents_str',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='children_commit',
        ),
    ]
