# Generated by Django 2.2.5 on 2019-11-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0015_auto_20191107_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='children_commit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='contributions.Commit'),
        ),
    ]
