# Generated by Django 3.0 on 2019-12-17 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0018_auto_20191202_1142'),
    ]

    operations = [
    ]

    # def
