# Generated by Django 3.0 on 2019-12-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0019_auto_20191217_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='u_cloc',
            field=models.IntegerField(default=0),
        ),
    ]
