# Generated by Django 3.0 on 2019-12-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0020_modification_u_cloc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualcontribution',
            name='abs_experience',
        ),
        migrations.RemoveField(
            model_name='individualcontribution',
            name='ownership_cloc_in_this_tag',
        ),
        migrations.RemoveField(
            model_name='individualcontribution',
            name='ownership_commits_in_this_tag',
        ),
        migrations.RemoveField(
            model_name='individualcontribution',
            name='ownership_files_in_this_tag',
        ),
        migrations.AddField(
            model_name='individualcontribution',
            name='previous_individual_contribution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contributions.IndividualContribution'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='hash',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='modification',
            name='added',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modification',
            name='diff',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='modification',
            name='nloc',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='modification',
            name='path',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='removed',
            field=models.IntegerField(default=0),
        ),
    ]
