# Generated by Django 3.0 on 2019-12-28 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0021_auto_20191227_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='abs_experience',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='ownership_cloc_in_this_tag',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='ownership_commits_in_this_tag',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='ownership_files_in_this_tag',
        ),
        migrations.AddField(
            model_name='projectindividualcontribution',
            name='previous_individual_contribution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='contributions.ProjectIndividualContribution'),
        ),
        migrations.AlterField(
            model_name='individualcontribution',
            name='previous_individual_contribution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to='contributions.IndividualContribution'),
        ),
    ]
