# Generated by Django 3.0 on 2019-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0022_auto_20191227_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='nloc',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
