# Generated by Django 3.0 on 2019-12-28 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0023_auto_20191228_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directoryreport',
            name='directory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_reports',
                                    to='contributions.Directory'),
        ),
        migrations.AlterField(
            model_name='directoryreport',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directory_reports',
                                    to='contributions.Tag'),
        ),
        migrations.AlterField(
            model_name='individualcontribution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Developer'),
        ),
        migrations.AlterField(
            model_name='individualcontribution',
            name='directory_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.DirectoryReport'),
        ),
        migrations.AlterField(
            model_name='individualcontribution',
            name='previous_individual_contribution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='contributions.IndividualContribution'),
        ),
        migrations.AlterField(
            model_name='projectindividualcontribution',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Developer'),
        ),
        migrations.AlterField(
            model_name='projectindividualcontribution',
            name='previous_individual_contribution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='contributions.ProjectIndividualContribution'),
        ),
        migrations.AlterField(
            model_name='projectindividualcontribution',
            name='project_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.ProjectReport'),
        ),
        migrations.AlterField(
            model_name='projectreport',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_reports',
                                    to='contributions.Tag'),
        ),
    ]
