# Generated by Django 3.0 on 2019-12-28 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0024_auto_20191228_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='ownership_cloc',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='ownership_commits',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='ownership_files',
        ),
    ]
