# Generated by Django 3.0 on 2019-12-29 00:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0026_auto_20191228_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='author_date',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='committer_date',
        ),
    ]
