# Generated by Django 3.0 on 2019-12-29 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0028_auto_20191228_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=180),
            preserve_default=False,
        ),
    ]
