# Generated by Django 3.0 on 2019-12-29 00:48

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0029_commit_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='commit',
            name='children_commit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='contributions.Commit'),
        ),
        migrations.AddField(
            model_name='commit',
            name='committer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='committer_id',
                                    to='contributions.Developer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commit',
            name='committer_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='commit',
            name='msg',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='commit',
            name='parents_str',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id',
                                    to='contributions.Developer'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='hash',
            field=models.CharField(default='', max_length=180),
        ),
    ]
