# Generated by Django 3.0 on 2020-01-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0030_auto_20191228_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='parents_str',
            field=models.CharField(max_length=180),
        ),
    ]
