# Generated by Django 3.0 on 2020-01-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0031_auto_20200103_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='author_experience',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
