# Generated by Django 3.0 on 2020-01-04 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0032_commit_author_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='FileByAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Developer')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.File')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='authors',
            field=models.ManyToManyField(through='contributions.FileByAuthor', to='contributions.Developer'),
        ),
        migrations.AddField(
            model_name='modification',
            name='file_by_author',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='contributions.FileByAuthor'),
            preserve_default=False,
        ),
    ]
