# Generated by Django 3.0 on 2020-01-05 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0035_auto_20200103_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filebyauthor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files_by_author', to='contributions.Developer'),
        ),
    ]
