# Generated by Django 3.0 on 2020-01-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0036_auto_20200104_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='contributions.Developer'),
        ),
    ]
