# Generated by Django 3.0 on 2020-01-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0037_auto_20200105_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='cloc_activity_str',
            field=models.CharField(default='', max_length=220),
        ),
    ]
