# Generated by Django 3.0 on 2020-01-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0038_commit_cloc_activity_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='children_rel', to='contributions.Commit'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='children_commit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='parent_rel', to='contributions.Commit'),
        ),
    ]
