# Generated by Django 3.0 on 2020-01-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0038_commit_cloc_activity_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filebyauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='filebyauthor',
            name='file',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='file_by_author',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='FileByAuthor',
        ),
    ]
