# Generated by Django 3.0 on 2020-01-09 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0039_auto_20200109_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='parent',
        ),
    ]
