# Generated by Django 3.0 on 2020-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0040_remove_commit_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='compilable',
            field=models.BooleanField(default=False),
        ),
    ]
