# Generated by Django 3.0 on 2020-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0041_commit_compilable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='compilable',
            field=models.BooleanField(default=True),
        ),
    ]
