# Generated by Django 3.0 on 2020-02-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0044_auto_20200204_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='delta_total_rmd',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='mean_rmd',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='commit',
            name='std_rmd',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
