# Generated by Django 3.0 on 2020-02-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0047_auto_20200207_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='delta_rmd',
            new_name='delta_rmd_components',
        ),
    ]
