# Generated by Django 3.0 on 2020-02-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0048_auto_20200207_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='login',
            field=models.CharField(default='', max_length=60),
        ),
    ]
