# Generated by Django 3.0 on 2020-02-12 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0050_auto_20200212_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
