# Generated by Django 3.0 on 2020-02-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0051_auto_20200212_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='architecture_change',
        ),
        migrations.AlterField(
            model_name='directory',
            name='visible',
            field=models.BooleanField(default=False),
        ),
    ]
