# Generated by Django 3.0 on 2020-02-13 14:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0052_auto_20200212_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
