# Generated by Django 3.0 on 2020-02-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0053_auto_20200213_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='changed_architecture',
            field=models.BooleanField(default=False),
        ),
    ]
