# Generated by Django 3.0 on 2020-02-17 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0001_initial'),
        ('contributions', '0054_commit_changed_architecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='analysis_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dataanalysis.AnalysisPeriod'),
        ),
    ]
