# Generated by Django 3.0 on 2020-03-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0056_auto_20200320_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='hasSubmittedBy',
            field=models.BooleanField(default=False),
        ),
    ]
