# Generated by Django 3.0 on 2020-03-28 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0057_commit_hassubmittedby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='hasSubmittedBy',
            new_name='has_submitted_by',
        ),
    ]
