# Generated by Django 3.0 on 2020-04-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0058_auto_20200328_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='delta_rmd_components',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
