# Generated by Django 3.0 on 2020-04-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0059_tag_delta_rmd_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='normalized_delta',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
