# Generated by Django 3.0 on 2020-04-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0063_auto_20200415_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='max_minor_version_description',
            field=models.CharField(default='', max_length=80),
        ),
    ]
