# Generated by Django 3.0 on 2020-04-16 22:04

from django.db import migrations


class Migration(migrations.Migration):

    def update_tags_max_minor_version(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        Tag = apps.get_model('contributions', 'Tag')

        for tag in Tag.objects.all():
            if tag.description == 'rel/1.4':
                tag.max_minor_version_description = 'ANT_141'
            elif tag.description == 'rel/1.5':
                tag.max_minor_version_description = 'rel/1.5.1,rel/1.5.2,rel/1.5.3,rel/1.5.4'
            elif tag.description == 'rel/1.6.0':
                tag.max_minor_version_description = 'rel/1.6.1,rel/1.6.2,rel/1.6.3,rel/1.6.4,rel/1.6.5'
            elif tag.description == 'rel/1.7.0':
                tag.max_minor_version_description = 'rel/1.7.1'
            elif tag.description == 'rel/1.8.0':
                tag.max_minor_version_description = 'rel/1.8.1,rel/1.8.2,rel/1.8.3,rel/1.8.4'
            elif tag.description == 'rel/1.9.0':
                tag.max_minor_version_description = 'rel/1.9.1,rel/1.9.2,rel/1.9.3,rel/1.9.4,rel/1.9.5,rel/1.9.6,' \
                                                    'rel/1.9.7,rel/1.9.8,rel/1.9.9,rel/1.9.10,rel/1.9.11,' \
                                                    'rel/1.9.12,rel/1.9.13,rel/1.9.14,rel/1.9.14'
            elif tag.description == 'rel/1.10.0':
                tag.max_minor_version_description = 'rel/1.10.1,rel/1.10.2,rel/1.10.3,rel/1.10.4,rel/1.10.5,' \
                                                    'rel/1.10.6,rel/1.10.7'
            tag.save()

    dependencies = [
        ('contributions', '0065_tag_max_minor_version_description'),
    ]

    operations = [
        migrations.RunPython(update_tags_max_minor_version),
    ]
