# Generated by Django 3.0 on 2020-04-17 16:15

from django.db import migrations


class Migration(migrations.Migration):

    def update_tags_max_minor_version(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        tag = apps.get_model('contributions', 'Tag')
        project = apps.get_model('contributions', 'Project')

        apache = project.objects.get_or_create(project_name='Apache Ant')


    dependencies = [
        ('contributions', '0068_tag_major'),
    ]

    operations = [
        migrations.RunPython(update_tags_max_minor_version),
    ]
