# Generated by Django 3.0 on 2020-04-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0070_auto_20200424_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcommit',
            name='cloc_accumulation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='componentcommit',
            name='commits_accumulation',
            field=models.IntegerField(default=0),
        ),
    ]
