# Generated by Django 3.0 on 2020-04-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    def update_tags_max_minor_version(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        tag = apps.get_model('contributions', 'Tag')
        project = apps.get_model('contributions', 'Project')

    dependencies = [
        ('contributions', '0071_auto_20200424_1312'),
    ]

    operations = [
        migrations.RunPython(update_tags_max_minor_version),
    ]
