# Generated by Django 3.0 on 2020-04-29 01:17

from django.db import migrations


class Migration(migrations.Migration):

    def fix_experience(apps, schema_editor):
        # We can't import the Person model directly as it may be a newer
        # version than this migration expects. We use the historical version.
        commit = apps.get_model('contributions', 'Commit')

        for commit in commit.objects.filter(tag_id=23).order_by('id'):
            if len(commit.modifications.all()) == 0:
                instance = commit.objects.get(id=commit.id)
                instance.delete()

    dependencies = [
        ('contributions', '0073_auto_20200427_1127'),
    ]

    operations = [
        migrations.RunPython(fix_experience),
    ]
