# Generated by Django 3.0 on 2020-05-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0076_auto_20200428_2222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['tag_id', 'id']},
        ),
        migrations.AddField(
            model_name='project',
            name='core_component',
            field=models.CharField(default='', max_length=120),
        ),
    ]
