# Generated by Django 3.0 on 2020-05-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0077_auto_20200511_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_directory',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tag',
            name='build_command',
            field=models.CharField(default='ant compile', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='prepare_build_command',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
