# Generated by Django 3.0 on 2020-05-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0078_auto_20200513_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_branch',
            field=models.CharField(default='master', max_length=80),
        ),
    ]
