# Generated by Django 3.0 on 2020-05-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0079_project_main_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='core_component',
        ),
        migrations.RemoveField(
            model_name='project',
            name='main_directory',
        ),
        migrations.AddField(
            model_name='tag',
            name='core_component',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AddField(
            model_name='tag',
            name='main_directory',
            field=models.CharField(default='', max_length=280),
        ),
        migrations.AlterField(
            model_name='tag',
            name='build_command',
            field=models.CharField(default='ant compile', max_length=399),
        ),
        migrations.AlterField(
            model_name='tag',
            name='prepare_build_command',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
