# Generated by Django 3.0 on 2020-05-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0080_auto_20200517_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='max_minor_version_description',
            field=models.TextField(default=''),
        ),
    ]
