# Generated by Django 3.0 on 2020-05-17 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0081_auto_20200517_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='previous_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.Tag'),
        ),
    ]
