# Generated by Django 3.0 on 2020-05-17 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0082_auto_20200517_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='previous_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contributions.Tag'),
        ),
    ]
