# Generated by Django 3.0 on 2020-05-25 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0084_auto_20200517_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='metrics_calculated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
