# Generated by Django 3.0 on 2020-05-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0085_tag_metrics_calculated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='metrics_calculated_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
