# Generated by Django 3.0 on 2020-05-26 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0087_remove_tag_metrics_calculated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.AddField(
            model_name='tag',
            name='alias',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
