# Generated by Django 3.0 on 2020-05-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0088_auto_20200525_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
