# Generated by Django 3.0 on 2020-05-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0089_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='alias',
        ),
        migrations.AddField(
            model_name='tag',
            name='real_tag_description',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
    ]
