# Generated by Django 3.0.7 on 2020-07-02 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0091_auto_20200528_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='has_impact_loc',
            field=models.BooleanField(default=False),
        ),
    ]
