# Generated by Django 3.0.8 on 2020-07-21 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0093_componentcommit_commit_str'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directoryreport',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='directoryreport',
            name='directory',
        ),
        migrations.RemoveField(
            model_name='directoryreport',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='individualcontribution',
            name='author',
        ),
        migrations.RemoveField(
            model_name='individualcontribution',
            name='directory_report',
        ),
        migrations.RemoveField(
            model_name='individualcontribution',
            name='previous_individual_contribution',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='previous_individual_contribution',
        ),
        migrations.RemoveField(
            model_name='projectindividualcontribution',
            name='project_report',
        ),
        migrations.RemoveField(
            model_name='projectreport',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='projectreport',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ContributionByAuthorReport',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='MetricsReport',
        ),
        migrations.DeleteModel(
            name='DirectoryReport',
        ),
        migrations.DeleteModel(
            name='IndividualContribution',
        ),
        migrations.DeleteModel(
            name='ProjectIndividualContribution',
        ),
        migrations.DeleteModel(
            name='ProjectReport',
        ),
    ]
