# Generated by Django 3.0.8 on 2020-07-21 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0094_auto_20200721_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='previous_impactful_commit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_impactful_commit_rel', to='contributions.Commit'),
        ),
    ]
