# Generated by Django 3.0.8 on 2020-07-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0095_commit_previous_impactful_commit'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentcommit',
            name='delta_rmd',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='componentcommit',
            name='rmd',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
