# Generated by Django 3.2.7 on 2021-12-05 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0054_commit_changed_architecture'),
        ('contributions', '0097_alter_commit_compilable'),
    ]

    operations = [
    ]
