# Generated by Django 3.2.7 on 2021-12-09 02:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0098_merge_20211205_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modification',
            name='complexity',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='nloc',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='source_code',
        ),
        migrations.RemoveField(
            model_name='modification',
            name='source_code_before',
        ),
    ]
