# Generated by Django 3.2.7 on 2021-12-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0099_auto_20211208_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
