global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "django_app"
    static_configs:
      #      - targets: [ "statsd-exporter:9102" ]
      - targets: [ 'host.docker.internal:8080' ]