# Generated by Django 2.2.5 on 2019-11-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contributions', '0016_commit_children_commit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compiled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hash_commit', models.CharField(max_length=300)),
                ('filename', models.CharField(max_length=300)),
                ('quality_delta', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compileds',
                                              to='contributions.Project')),
            ],
        ),
    ]
