# Generated by Django 2.2.5 on 2019-11-07 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiled',
            name='previous_compiled',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='architecture.Compiled'),
        ),
    ]
