# Generated by Django 2.2.5 on 2019-11-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0017_auto_20191122_1302'),
        ('architecture', '0003_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureQualityByDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureQualityMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmd', models.FloatField(default=0.0, null=True)),
                ('rma', models.FloatField(default=0.0, null=True)),
                ('rmi', models.FloatField(default=0.0, null=True)),
                ('ca', models.FloatField(default=0.0, null=True)),
                ('ce', models.FloatField(default=0.0, null=True)),
                ('commit',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectural_metrics',
                                   to='contributions.Commit')),
                ('directory',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Directory')),
                ('previous_architecture_quality_metrics',
                 models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   to='architecture.ArchitectureQualityMetrics')),
            ],
        ),
        migrations.CreateModel(
            name='FileCommits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('directory', models.CharField(max_length=100)),
                ('has_compileds', models.BooleanField(default=False)),
                ('build_path', models.CharField(max_length=200)),
                ('local_repository',
                 models.CharField(default='G:/My Drive/MestradoUSP/programacao/projetos/git/ant', max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                              to='contributions.Project')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='compiled',
            name='project',
        ),
        migrations.AddField(
            model_name='architecturequalitybydeveloper',
            name='architecture_quality_metrics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_by_developer',
                                    to='architecture.ArchitectureQualityMetrics'),
        ),
        migrations.AddField(
            model_name='architecturequalitybydeveloper',
            name='developer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_id',
                                    to='contributions.Developer'),
        ),
        migrations.AddField(
            model_name='compiled',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compileds',
                                    to='architecture.FileCommits'),
            preserve_default=False,
        ),
    ]
