# Generated by Django 2.2.5 on 2019-11-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('architecture', '0004_auto_20191128_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecturequalitymetrics',
            name='ca',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='architecturequalitymetrics',
            name='ce',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
