# Generated by Django 2.2.5 on 2019-11-12 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0004_compiled_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compiled',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compileds', to='architecture.File'),
        ),
    ]
