# Generated by Django 2.2.5 on 2019-11-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0017_auto_20191122_1302'),
        ('architecture', '0005_auto_20191128_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturequalitybydeveloper',
            name='architecture_quality_metrics',
        ),
        migrations.RemoveField(
            model_name='architecturequalitymetrics',
            name='directory',
        ),
        migrations.AddField(
            model_name='architecturequalitybydeveloper',
            name='directory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contributions.Directory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architecturequalitybydeveloper',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contributions.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='architecturequalitymetrics',
            name='architecture_quality_by_developer_and_directory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='architecture.ArchitectureQualityByDeveloper'),
            preserve_default=False,
        ),
    ]
