# Generated by Django 2.2.5 on 2019-11-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0005_auto_20191112_1151'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='FileCommits',
        ),
    ]
