# Generated by Django 2.2.5 on 2019-11-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0016_commit_children_commit'),
        ('architecture', '0006_auto_20191112_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compiled',
            name='project',
        ),
        migrations.AddField(
            model_name='filecommits',
            name='local_repository',
            field=models.CharField(default='G:/My Drive/MestradoUSP/programacao/projetos/git/ant', max_length=200),
        ),
        migrations.AddField(
            model_name='filecommits',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contributions.Project'),
            preserve_default=False,
        ),
    ]
