# Generated by Django 2.2.5 on 2019-12-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0006_auto_20191129_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Compiled',
        ),
    ]
