# Generated by Django 2.2.5 on 2019-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0007_auto_20191112_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecommits',
            name='build_path',
            field=models.CharField(default='build', max_length=200),
            preserve_default=False,
        ),
    ]
