# Generated by Django 3.0 on 2019-12-20 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0020_modification_u_cloc'),
        ('architecture', '0008_auto_20191212_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturequalitybydeveloper',
            name='developer',
        ),
        migrations.AddField(
            model_name='architecturequalitybydeveloper',
            name='project_individual_contribution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='project_individual_contribution_id',
                                    to='contributions.ProjectIndividualContribution'),
            preserve_default=False,
        ),
    ]
