# Generated by Django 2.2.5 on 2019-11-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0017_auto_20191122_1302'),
        ('architecture', '0008_filecommits_build_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectureQualityMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmd', models.FloatField(default=0.0, null=True)),
                ('rma', models.FloatField(default=0.0, null=True)),
                ('rmi', models.FloatField(default=0.0, null=True)),
                ('ca', models.FloatField(default=0.0, null=True)),
                ('ce', models.FloatField(default=0.0, null=True)),
                ('directory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contributions.Directory')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='architecture_quality_metrics', to='contributions.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='ArchitectureQualityByDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('architecture_quality_metrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics_by_developer', to='architecture.ArchitectureQualityMetrics')),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developer_id', to='contributions.Developer')),
            ],
        ),
    ]
