# Generated by Django 3.0 on 2020-01-07 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('architecture', '0012_auto_20200107_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchitectureQualityByDeveloper',
        ),
    ]
