# Generated by Django 3.0 on 2020-01-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0013_delete_architecturequalitybydeveloper'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturalmetricsbycommit',
            name='delta_rmd',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
