# Generated by Django 3.0 on 2020-04-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0014_architecturalmetricsbycommit_delta_rmd'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturalmetricsbycommit',
            name='author_experience',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='architecturalmetricsbycommit',
            name='cloc_accumulation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='architecturalmetricsbycommit',
            name='commits_accumulation',
            field=models.IntegerField(default=0),
        ),
    ]
