# Generated by Django 3.0 on 2020-04-24 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contributions', '0071_auto_20200424_1312'),
        ('architecture', '0023_auto_20200424_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecturalmetricsbycommit',
            name='component_commit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='architectural_metrics', to='contributions.ComponentCommit'),
        ),
    ]
