# Generated by Django 3.0 on 2020-04-24 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0071_auto_20200424_1312'),
        ('architecture', '0024_auto_20200424_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturalmetricsbycommit',
            name='commit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='architectural_metrics', to='contributions.Commit'),
            preserve_default=False,
        ),
    ]
