# Generated by Django 3.0 on 2020-05-12 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0025_architecturalmetricsbycommit_commit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='architecturalmetricsbycommit',
            name='author_experience',
        ),
    ]
