# Generated by Django 3.0 on 2020-05-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('architecture', '0026_remove_architecturalmetricsbycommit_author_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecommits',
            name='metrics_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
