# Generated by Django 3.0.8 on 2020-07-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0040_auto_20200711_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='architecturalmetricsbycommit',
            name='commit_str',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
