# Generated by Django 3.0.8 on 2020-07-14 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0093_componentcommit_commit_str'),
        ('architecture', '0041_architecturalmetricsbycommit_commit_str'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architecturalmetricsbycommit',
            name='commit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='architectural_metrics', to='contributions.Commit'),
        ),
    ]
