# Generated by Django 3.0.8 on 2020-07-22 22:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('architecture', '0042_auto_20200713_2132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchitecturalMetricsByCommit',
        ),
    ]
