# Generated by Django 3.0 on 2020-02-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0055_commit_analysis_period'),
        ('dataanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisperiod',
            name='end_commit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_period_ending', to='contributions.Commit'),
        ),
    ]
