# Generated by Django 3.0 on 2020-02-17 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0055_commit_analysis_period'),
        ('dataanalysis', '0002_auto_20200217_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisperiod',
            name='end_commit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis_period_ending', to='contributions.Commit'),
        ),
        migrations.AlterField(
            model_name='analysisperiod',
            name='start_commit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='analysis_period_beginning', to='contributions.Commit'),
        ),
    ]
