# Generated by Django 3.0 on 2020-04-23 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataanalysis', '0006_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
